# roles/user_management/tasks/disable_ssh_login.yml
- name: Disable SSH login for user
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /usr/sbin/nologin
  register: user_result

- name: Lock user's password
  ansible.builtin.user:
    name: "{{ username }}"
    password_lock: yes
  when: user_result is not failed

- name: Remove SSH authorized keys
  ansible.builtin.file:
    path: "/home/{{ username }}/.ssh/authorized_keys"
    state: absent
  when: user_result is not failed
  ignore_errors: true
